//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WS.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosSoap")]
    public interface ServiciosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsultaMontoOrdenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConsultaMontoOrdenes(int Orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsultaMontoOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConsultaMontoOrdenesAsync(int Orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroOrdenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNumeroOrdenes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumeroOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetNumeroOrdenesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : Client_WS.ServiceReference1.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<Client_WS.ServiceReference1.ServiciosSoap>, Client_WS.ServiceReference1.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetConsultaMontoOrdenes(int Orden) {
            return base.Channel.GetConsultaMontoOrdenes(Orden);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConsultaMontoOrdenesAsync(int Orden) {
            return base.Channel.GetConsultaMontoOrdenesAsync(Orden);
        }
        
        public System.Data.DataSet GetNumeroOrdenes() {
            return base.Channel.GetNumeroOrdenes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetNumeroOrdenesAsync() {
            return base.Channel.GetNumeroOrdenesAsync();
        }
    }
}
